/* ============================================================================
   BANCO DE DADOS: FPC_DIAGNOSTICS (Firebird 5.0)
   DIALETO: 3 | CHARSET: UTF8 | COLLATION: UNICODE_CI_AI
   OBJETIVO: Catálogo de Diagnósticos, Mensagens e Quick Fixes do FPC
   ============================================================================ */

/* 1. CRIAÇÃO DE TABELAS */

CREATE TABLE FPC_MESSAGES (
    ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CODE INTEGER NOT NULL,
    SEVERITY VARCHAR(10) NOT NULL,
    MESSAGE_PATTERN VARCHAR(255) NOT NULL,
    DESCRIPTION_PTBR BLOB SUB_TYPE TEXT,
    PROBABLE_CAUSE BLOB SUB_TYPE TEXT,
    MANUAL_SOLUTION BLOB SUB_TYPE TEXT,
    CAN_AUTO_FIX CHAR(1) DEFAULT 'N' NOT NULL,
    AUTO_FIX_STRATEGY VARCHAR(255),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT UK_FPC_MESSAGES_CODE UNIQUE (CODE),
    CONSTRAINT CHK_FPC_MESSAGES_SEVERITY CHECK (SEVERITY IN ('HINT', 'NOTE', 'WARNING', 'ERROR', 'FATAL')),
    CONSTRAINT CHK_FPC_MESSAGES_CAN_AUTO_FIX CHECK (CAN_AUTO_FIX IN ('S', 'N'))
);

/* 2. ÍNDICES DE PERFORMANCE */
CREATE INDEX IDX_FPC_MESSAGES_SEVERITY ON FPC_MESSAGES (SEVERITY);
CREATE INDEX IDX_FPC_MESSAGES_AUTO_FIX ON FPC_MESSAGES (CAN_AUTO_FIX);

/* 3. TRIGGER DE AUDITORIA (ATUALIZAÇÃO AUTOMÁTICA DE UPDATED_AT) */
SET TERM ^ ;
CREATE OR ALTER TRIGGER TRG_FPC_MESSAGES_BU FOR FPC_MESSAGES
ACTIVE BEFORE UPDATE POSITION 0
AS
BEGIN
    NEW.UPDATED_AT = CURRENT_TIMESTAMP;
END^
SET TERM ; ^

/* ============================================================================
   4. CARGA INICIAL DE DADOS (SEED SQL)
   ============================================================================ */

-- 5023: Parameter "$1" not used
INSERT INTO FPC_MESSAGES (
    CODE, SEVERITY, MESSAGE_PATTERN, DESCRIPTION_PTBR, PROBABLE_CAUSE,
    MANUAL_SOLUTION, CAN_AUTO_FIX, AUTO_FIX_STRATEGY
) VALUES (
    5023,
    'HINT',
    'Parameter "$1" not used',
    'O parâmetro foi formalmente declarado na assinatura da rotina (procedure/function/method), porém nenhum comando no bloco de execução lê ou utiliza seu valor.',
    'Assinaturas obrigatórias impostas por contratos de eventos da LCL/VCL (como "Sender: TObject" em TNotifyEvent), herança de métodos virtuais onde apenas certas subclasses precisam do parâmetro, ou métodos de interface.',
    '1. No Free Pascal / Lazarus, utilize a diretiva canônica {%H-} imediatamente antes do parâmetro na declaração para silenciar o aviso mantendo a assinatura válida:' || ASCII_CHAR(10) ||
    '   Exemplo: procedure TForm1.MeuBotaoClick({%H-}Sender: TObject);' || ASCII_CHAR(10) ||
    '2. Caso seja um método particular/interno não vinculado a evento, remova o parâmetro não utilizado para limpar a API.' || ASCII_CHAR(10) ||
    '3. Caso o parâmetro tenha sido esquecido, implemente seu uso na lógica.',
    'S',
    'InsertParamUnusedDirective'
);

-- 5024: Variable "$1" not used
INSERT INTO FPC_MESSAGES (
    CODE, SEVERITY, MESSAGE_PATTERN, DESCRIPTION_PTBR, PROBABLE_CAUSE,
    MANUAL_SOLUTION, CAN_AUTO_FIX, AUTO_FIX_STRATEGY
) VALUES (
    5024,
    'HINT',
    'Variable "$1" not used',
    'Uma variável foi declarada no escopo local ou global (seção "var"), mas nunca é lida, modificada ou referenciada por nenhuma instrução subsequente.',
    'Código legado após refatoração, variáveis de iteração que foram substituídas por for..in, ou declaração de variáveis para testes que não foram removidas.',
    '1. Remova a linha de declaração da variável na seção "var" correspondente.' || ASCII_CHAR(10) ||
    '2. Se a variável for necessária para depuração ou trabalho em andamento, prefixe-a com a diretiva {%H-}:' || ASCII_CHAR(10) ||
    '   Exemplo: {%H-}MinhaVar: Integer;',
    'S',
    'RemoveUnusedVariableDeclaration'
);

-- 5025: Unit "$1" not used in $2
INSERT INTO FPC_MESSAGES (
    CODE, SEVERITY, MESSAGE_PATTERN, DESCRIPTION_PTBR, PROBABLE_CAUSE,
    MANUAL_SOLUTION, CAN_AUTO_FIX, AUTO_FIX_STRATEGY
) VALUES (
    5025,
    'HINT',
    'Unit "$1" not used in $2',
    'A unit especificada foi importada na cláusula "uses" (seja da seção interface ou implementation), mas nenhum tipo, rotina, constante ou variável dela é referenciada na unit atual.',
    'Remoção de componentes do formulário que deixaram dependências na cláusula uses, cópia e colagem de cabeçalhos de outras units, ou refatorações sucessivas.',
    'Remova a unit indicada da lista da cláusula "uses". Isso acelera o tempo de compilação, evita acoplamento desnecessário, elimina dependências circulares e reduz o grafo de compilação da aplicação.',
    'S',
    'RemoveUnitFromUses'
);

-- 5036: Local variable "$1" is assigned but never used
INSERT INTO FPC_MESSAGES (
    CODE, SEVERITY, MESSAGE_PATTERN, DESCRIPTION_PTBR, PROBABLE_CAUSE,
    MANUAL_SOLUTION, CAN_AUTO_FIX, AUTO_FIX_STRATEGY
) VALUES (
    5036,
    'NOTE',
    'Local variable "$1" is assigned but never used',
    'A variável local recebe valores através de atribuição explícita (:=) ou via parâmetro "out", mas o conteúdo armazenado nunca é lido ou utilizado em cálculos posteriores.',
    'Cálculo intermediário que se tornou obsoleto após mudança de regra de negócio, ou chamada de função onde o desenvolvedor capturou o retorno em variável mas não precisou utilizá-lo.',
    '1. Se a chamada à direita do operador := gerar efeitos colaterais indispensáveis, execute a chamada diretamente sem atribuir à variável (ou descarte-a).' || ASCII_CHAR(10) ||
    '2. Se o cálculo for supérfluo, remova a atribuição e a declaração da variável.' || ASCII_CHAR(10) ||
    '3. Se o valor deveria ter sido consumido, inspecione a lógica para verificar se não houve omissão de uso.',
    'N',
    'ManualRefactor'
);

-- 5057: Local variable "$1" does not seem to be initialized
INSERT INTO FPC_MESSAGES (
    CODE, SEVERITY, MESSAGE_PATTERN, DESCRIPTION_PTBR, PROBABLE_CAUSE,
    MANUAL_SOLUTION, CAN_AUTO_FIX, AUTO_FIX_STRATEGY
) VALUES (
    5057,
    'WARNING',
    'Local variable "$1" does not seem to be initialized',
    'Uma variável local alocada na pilha (stack) é lida antes de ter uma atribuição de valor prévia garantida em todos os fluxos de execução do método.',
    'Em Object Pascal, variáveis locais da pilha contêm lixo residual de memória. Esse aviso ocorre com frequência quando a inicialização da variável ocorre dentro de um bloco condicional (if/case) que pode ser ignorado em tempo de execução.',
    'Atribua um valor inicial explícito e determinístico logo no início do bloco begin/end da rotina:' || ASCII_CHAR(10) ||
    '   - Numéricos: X := 0;' || ASCII_CHAR(10) ||
    '   - Strings: S := '''';' || ASCII_CHAR(10) ||
    '   - Objetos/Ponteiros: P := nil;' || ASCII_CHAR(10) ||
    '   - Records complexos: FillChar(MeuRecord, SizeOf(MeuRecord), 0);',
    'S',
    'InsertVariableDefaultInitialization'
);

-- 5058: Variable "$1" does not seem to be initialized
INSERT INTO FPC_MESSAGES (
    CODE, SEVERITY, MESSAGE_PATTERN, DESCRIPTION_PTBR, PROBABLE_CAUSE,
    MANUAL_SOLUTION, CAN_AUTO_FIX, AUTO_FIX_STRATEGY
) VALUES (
    5058,
    'WARNING',
    'Variable "$1" does not seem to be initialized',
    'Uma variável não-local (global, estática de unit ou parâmetro de saída não preenchido) é consultada sem garantia de inicialização prévia.',
    'Fluxo assíncrono ou ordem de execução onde a variável é consultada antes da rotina de setup ter sido disparada, ou passagem de variável como parâmetro sem inicialização prévia.',
    'Garanta a inicialização da variável antes de qualquer operação de leitura, preferencialmente na seção "initialization" da unit ou no construtor do módulo responsável.',
    'N',
    'ManualRefactor'
);

-- 4055: Conversion between ordinals and pointers is not portable
INSERT INTO FPC_MESSAGES (
    CODE, SEVERITY, MESSAGE_PATTERN, DESCRIPTION_PTBR, PROBABLE_CAUSE,
    MANUAL_SOLUTION, CAN_AUTO_FIX, AUTO_FIX_STRATEGY
) VALUES (
    4055,
    'WARNING',
    'Conversion between ordinals and pointers is not portable',
    'Conversão direta (typecast) entre um tipo ponteiro e um tipo ordinal de tamanho fixo (como Integer ou Cardinal). Em plataformas 64 bits, isso resulta em truncamento e violação de acesso.',
    'Código legado escrito na era 32 bits (onde ponteiros e Integer tinham ambos 4 bytes) migrado para 64 bits (onde ponteiros têm 8 bytes e Integer mantém 4 bytes). Ao fazer Integer(Ptr), os 32 bits mais significativos são descartados.',
    'Substitua os tipos ordinais rígidos pelos tipos de tamanho equivalente ao ponteiro da arquitetura alvo:' || ASCII_CHAR(10) ||
    '   - Para inteiros com sinal: utilize PtrInt(MeuPonteiro) em vez de Integer(MeuPonteiro);' || ASCII_CHAR(10) ||
    '   - Para inteiros sem sinal: utilize PtrUInt(MeuPonteiro) em vez de Cardinal/DWord(MeuPonteiro);' || ASCII_CHAR(10) ||
    '   - Para converter de volta para ponteiro: Pointer(PtrUInt(MeuValor)).',
    'S',
    'ReplaceOrdinalWithPtrInt'
);

-- 3187: Function result does not seem to be set
INSERT INTO FPC_MESSAGES (
    CODE, SEVERITY, MESSAGE_PATTERN, DESCRIPTION_PTBR, PROBABLE_CAUSE,
    MANUAL_SOLUTION, CAN_AUTO_FIX, AUTO_FIX_STRATEGY
) VALUES (
    3187,
    'WARNING',
    'Function result does not seem to be set',
    'A função pode terminar sua execução (alcançando o final do bloco ou saindo via Exit) sem que a variável implícita "Result" tenha recebido um valor em todos os caminhos lógicos.',
    'Ramificações condicionais (if..then sem else, ou blocos try..except) em que algumas condições deixam de definir o Result, ou rotinas alteradas de procedure para function.',
    '1. Atribua um valor padrão defensivo na primeira linha do corpo da função (ex: Result := False; ou Result := ''''; ou Result := nil;).' || ASCII_CHAR(10) ||
    '2. Revise todas as cláusulas condicionais para certificar-se de que cada ramo define explicitamente o Result.',
    'S',
    'InsertResultDefaultInitialization'
);

-- 3018: An inherited method is hidden by "$1"
INSERT INTO FPC_MESSAGES (
    CODE, SEVERITY, MESSAGE_PATTERN, DESCRIPTION_PTBR, PROBABLE_CAUSE,
    MANUAL_SOLUTION, CAN_AUTO_FIX, AUTO_FIX_STRATEGY
) VALUES (
    3018,
    'WARNING',
    'An inherited method is hidden by "$1"',
    'A classe descendente declarou um método com o mesmo nome de um método da classe mãe, sem utilizar a diretiva "override;" ou "reintroduce;".',
    'Esquecimento da cláusula "override;" para métodos polimórficos virtuais, ou criação intencional de um novo método com parâmetros diferentes que oculta o ancestral sem declarar a intenção com "reintroduce;".',
    '1. Se a intenção for sobrescrever o comportamento polimórfico do método virtual ancestral, declare "override;" no final da assinatura.' || ASCII_CHAR(10) ||
    '2. Se a intenção for introduzir um novo método com assinatura distinta ocultando o ancestral, declare "reintroduce;".',
    'S',
    'InsertOverrideOrReintroduceDirective'
);

-- 4056: Conversion between pointers and ordinals is not portable
INSERT INTO FPC_MESSAGES (
    CODE, SEVERITY, MESSAGE_PATTERN, DESCRIPTION_PTBR, PROBABLE_CAUSE,
    MANUAL_SOLUTION, CAN_AUTO_FIX, AUTO_FIX_STRATEGY
) VALUES (
    4056,
    'WARNING',
    'Conversion between pointers and ordinals is not portable',
    'Conversão direta de um número inteiro ordinal para um tipo ponteiro (ex: Pointer(MeuInteiro)). Em 64 bits, números inteiros de 32 bits não preenchem a largura total do registrador de endereço.',
    'Uso de inteiros para transportar handles de janelas ou apontadores em rotinas genéricas.',
    'Utilize Pointer(PtrUInt(Valor)) ou Pointer(PtrInt(Valor)) para garantir a extensão de sinal ou zeros correta nos 64 bits do endereço.',
    'S',
    'ReplacePointerCastWithPtrUInt'
);

-- 4035: Constructing a class "$1" with abstract methods
INSERT INTO FPC_MESSAGES (
    CODE, SEVERITY, MESSAGE_PATTERN, DESCRIPTION_PTBR, PROBABLE_CAUSE,
    MANUAL_SOLUTION, CAN_AUTO_FIX, AUTO_FIX_STRATEGY
) VALUES (
    4035,
    'WARNING',
    'Constructing a class "$1" with abstract methods',
    'Tentativa de instanciar diretamente uma classe que possui um ou mais métodos declarados como "virtual; abstract;" sem que tenham sido implementados.',
    'Instanciação direta de classe base/abstrata em vez de sua especialização concreta, ou esquecimento de implementar métodos abstratos herdados.',
    '1. Implemente todos os métodos abstratos na subclasse utilizando a diretiva "override;".' || ASCII_CHAR(10) ||
    '2. Ou altere o código para instanciar a subclasse concreta apropriada em vez da classe abstrata.',
    'N',
    'ManualRefactor'
);

-- 5000: Identifier not found "$1"
INSERT INTO FPC_MESSAGES (
    CODE, SEVERITY, MESSAGE_PATTERN, DESCRIPTION_PTBR, PROBABLE_CAUSE,
    MANUAL_SOLUTION, CAN_AUTO_FIX, AUTO_FIX_STRATEGY
) VALUES (
    5000,
    'ERROR',
    'Identifier not found "$1"',
    'O compilador não conseguiu resolver o símbolo (variável, constante, tipo, função ou procedimento) com o nome informado.',
    'Erro de digitação no nome do identificador, ausência da unit que o define na cláusula "uses", ou falta de qualificação de escopo (ex: esquecer de colocar "Objeto.Metodo").',
    '1. Verifique a ortografia do nome referenciado.' || ASCII_CHAR(10) ||
    '2. Adicione a unit proprietária do símbolo na cláusula uses da interface ou implementation.' || ASCII_CHAR(10) ||
    '3. Qualifique o identificador com o nome da instância ou classe correspondente.',
    'N',
    'ManualRefactor'
);

-- 10022: Can''t find unit "$1" used by "$2"
INSERT INTO FPC_MESSAGES (
    CODE, SEVERITY, MESSAGE_PATTERN, DESCRIPTION_PTBR, PROBABLE_CAUSE,
    MANUAL_SOLUTION, CAN_AUTO_FIX, AUTO_FIX_STRATEGY
) VALUES (
    10022,
    'FATAL',
    'Can''t find unit "$1" used by "$2"',
    'O compilador FPC não encontrou nem o código-fonte (.pas / .pp) nem a interface pré-compilada (.ppu) da unit indicada.',
    'Caminho de busca das units não configurado (-Fu), nome do arquivo divergente do nome declarado no cabeçalho da unit (case sensitivity no Linux), ou pacote de dependência não instalado.',
    '1. No Lazarus, acesse: Projeto > Opções do Projeto > Opções do Compilador > Caminhos, e adicione a pasta da unit em "Caminho de outras units (-Fu)".' || ASCII_CHAR(10) ||
    '2. Se a unit pertencer a um pacote externo, vá em Inspetor de Projeto > Adicionar > Novo Requisito e selecione o pacote.' || ASCII_CHAR(10) ||
    '3. No Linux, confirme que o nome do arquivo no disco possui exatamente as mesmas maiúsculas/minúsculas da cláusula uses.',
    'N',
    'ManualRefactor'
);

COMMIT;
